export default [
  { longName: 'Banco do Brasil S.A.', shortName: 'BCO DO BRASIL S.A.' },
  { longName: 'Banco da Amazônia S.A.', shortName: 'BCO DA AMAZONIA S.A.' },
  { longName: 'Banco do Nordeste do Brasil S.A.', shortName: 'BCO DO NORDESTE DO BRASIL S.A.' },
  { longName: 'BANCO NACIONAL DE DESENVOLVIMENTO ECONOMICO E SOCIAL', shortName: 'BNDES' },
  { longName: 'CREDICOAMO CREDITO RURAL COOPERATIVA', shortName: 'CREDICOAMO' },
  {
    longName: 'CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A',
    shortName: 'C.SUISSE HEDGING-GRIFFO CV S/A',
  },
  { longName: 'Banco Inbursa S.A.', shortName: 'BANCO INBURSA' },
  {
    longName: 'STATE STREET BRASIL S.A. - BANCO COMERCIAL',
    shortName: 'STATE STREET BR S.A. BCO COMERCIAL',
  },
  {
    longName: 'UBS Brasil Corretora de Câmbio Títulos e Valores Mobiliários S.A.',
    shortName: 'UBS BRASIL CCTVM S.A.',
  },
  {
    longName: 'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI',
    shortName: 'CCM DESP TRÂNS SC E RS',
  },
  { longName: 'BNY Mellon Banco S.A.', shortName: 'BNY MELLON BCO S.A.' },
  { longName: 'Banco Tricury S.A.', shortName: 'BCO TRICURY S.A.' },
  { longName: 'BANESTES S.A. Banco do Estado do Espírito Santo', shortName: 'BCO BANESTES S.A.' },
  { longName: 'Banco Bandepe S.A.', shortName: 'BCO BANDEPE S.A.' },
  { longName: 'Banco Alfa S.A.', shortName: 'BCO ALFA S.A.' },
  { longName: 'Banco Itaú Consignado S.A.', shortName: 'BANCO ITAÚ CONSIGNADO S.A.' },
  { longName: 'BANCO SANTANDER (BRASIL) S.A.', shortName: 'BCO SANTANDER (BRASIL) S.A.' },
  { longName: 'Banco Bradesco BBI S.A.', shortName: 'BCO BBI S.A.' },
  { longName: 'Banco do Estado do Pará S.A.', shortName: 'BCO DO EST. DO PA S.A.' },
  { longName: 'Banco Cargill S.A.', shortName: 'BCO CARGILL S.A.' },
  { longName: 'Banco do Estado do Rio Grande do Sul S.A.', shortName: 'BCO DO ESTADO DO RS S.A.' },
  { longName: 'Banco do Estado de Sergipe S.A.', shortName: 'BCO DO EST. DE SE S.A.' },
  { longName: 'Confidence Corretora de Câmbio S.A.', shortName: 'CONFIDENCE CC S.A.' },
  { longName: 'Hipercard Banco Múltiplo S.A.', shortName: 'HIPERCARD BM S.A.' },
  { longName: 'Banco Bradescard S.A.', shortName: 'BANCO BRADESCARD' },
  {
    longName: 'Goldman Sachs do Brasil Banco Múltiplo S.A.',
    shortName: 'GOLDMAN SACHS DO BRASIL BM S.A',
  },
  { longName: 'Banco AndBank (Brasil) S.A.', shortName: 'BCO ANDBANK S.A.' },
  { longName: 'BANCO MORGAN STANLEY S.A.', shortName: 'BCO MORGAN STANLEY S.A.' },
  { longName: 'Banco Crefisa S.A.', shortName: 'BCO CREFISA S.A.' },
  { longName: 'BRB - Banco de Brasília S.A.', shortName: 'BRB - BCO DE BRASILIA S.A.' },
  { longName: 'Banco J. Safra S.A.', shortName: 'BCO. J.SAFRA S.A.' },
  { longName: 'Banco ABN Amro S.A.', shortName: 'BCO ABN AMRO S.A.' },
  { longName: 'Banco KDB do Brasil S.A.', shortName: 'BCO KDB BRASIL S.A.' },
  { longName: 'Banco Inter S.A.', shortName: 'BANCO INTER' },
  {
    longName: 'Haitong Banco de Investimento do Brasil S.A.',
    shortName: 'HAITONG BI DO BRASIL S.A.',
  },
  { longName: 'Banco Original do Agronegócio S.A.', shortName: 'BCO ORIGINAL DO AGRO S/A' },
  { longName: 'B&T CORRETORA DE CAMBIO LTDA.', shortName: 'B&T CC LTDA.' },
  { longName: 'BancoSeguro S.A.', shortName: 'BANCOSEGURO S.A.' },
  { longName: 'BANCO TOPÁZIO S.A.', shortName: 'BANCO TOPÁZIO S.A.' },
  { longName: 'Banco da China Brasil S.A.', shortName: 'BCO DA CHINA BRASIL S.A.' },
  {
    longName: 'UNIPRIME NORTE DO PARANÁ - COOPERATIVA DE CRÉDITO LTDA',
    shortName: 'UNIPRIME NORTE DO PARANÁ - CC',
  },
  { longName: 'Cooperativa Central de Crédito - Ailos', shortName: 'COOPCENTRAL AILOS' },
  { longName: 'BANCO RANDON S.A.', shortName: 'BANCO RANDON S.A.' },
  { longName: 'CREDISAN COOPERATIVA DE CRÉDITO', shortName: 'CREDISAN CC' },
  {
    longName: 'CENTRAL DE COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO DO ESTADO DO RIO GRANDE DO S',
    shortName: 'CCCM UNICRED CENTRAL RS',
  },
  { longName: 'BRK S.A. Crédito Financiamento e Investimento', shortName: 'BRK S.A. CFI' },
  {
    longName: 'PÓLOCRED   SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT',
    shortName: 'POLOCRED SCMEPP LTDA.',
  },
  { longName: 'Banco Finaxis S.A.', shortName: 'BANCO FINAXIS' },
  { longName: 'Travelex Banco de Câmbio S.A.', shortName: 'TRAVELEX BANCO DE CÂMBIO S.A.' },
  { longName: 'Banco B3 S.A.', shortName: 'BCO B3 S.A.' },
  {
    longName: 'Credisis - Central de Cooperativas de Crédito Ltda.',
    shortName: 'CREDISIS CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.',
  },
  { longName: 'Credialiança Cooperativa de Crédito Rural', shortName: 'CREDIALIANÇA CCR' },
  {
    longName: 'UNIPRIME CENTRAL - CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.',
    shortName: 'UNIPRIME CENTRAL CCC LTDA.',
  },
  { longName: 'Planner Corretora de Valores S.A.', shortName: 'PLANNER CV S.A.' },
  {
    longName: 'RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    shortName: 'RENASCENCA DTVM LTDA',
  },
  {
    longName: 'XP INVESTIMENTOS CORRETORA DE CÂMBIOTÍTULOS E VALORES MOBILIÁRIOS S/A',
    shortName: 'XP INVESTIMENTOS CCTVM S/A',
  },
  { longName: 'Caixa Econômica Federal', shortName: 'CAIXA ECONOMICA FEDERAL' },
  { longName: 'Lecca Crédito Financiamento e Investimento S/A', shortName: 'LECCA CFI S.A.' },
  { longName: 'Banco Bocom BBM S.A.', shortName: 'BCO BOCOM BBM S.A.' },
  {
    longName: 'PORTOCRED S.A. - CREDITO FINANCIAMENTO E INVESTIMENTO',
    shortName: 'PORTOCRED S.A. - CFI',
  },
  {
    longName: 'OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.',
    shortName: 'OLIVEIRA TRUST DTVM S.A.',
  },
  { longName: 'MAGLIANO S.A. CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS', shortName: 'MAGLIANO' },
  {
    longName: 'Central Cooperativa de Crédito no Estado do Espírito Santo - CECOOP',
    shortName: 'CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO',
  },
  { longName: 'ADVANCED CORRETORA DE CÂMBIO LTDA', shortName: 'ADVANCED CC LTDA' },
  { longName: 'Banco Western Union do Brasil S.A.', shortName: 'BCO WESTERN UNION' },
  { longName: 'BANCO RODOBENS S.A.', shortName: 'BCO RODOBENS S.A.' },
  { longName: 'Banco Agibank S.A.', shortName: 'BCO AGIBANK S.A.' },
  { longName: 'Banco Bradesco BERJ S.A.', shortName: 'BCO BRADESCO BERJ S.A.' },
  { longName: 'Banco Woori Bank do Brasil S.A.', shortName: 'BCO WOORI BANK DO BRASIL S.A.' },
  { longName: 'BANCO GENIAL S.A.', shortName: 'BANCO GENIAL' },
  { longName: 'BR Partners Banco de Investimento S.A.', shortName: 'BR PARTNERS BI' },
  { longName: 'Codepe Corretora de Valores e Câmbio S.A.', shortName: 'CODEPE CVC S.A.' },
  { longName: 'MS Bank S.A. Banco de Câmbio', shortName: 'MS BANK S.A. BCO DE CÂMBIO' },
  { longName: 'UBS Brasil Banco de Investimento S.A.', shortName: 'UBS BRASIL BI S.A.' },
  {
    longName: 'CARUANA S.A. - SOCIEDADE DE CRÉDITO FINANCIAMENTO E INVESTIMENTO',
    shortName: 'CARUANA SCFI',
  },
  {
    longName: 'TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA',
    shortName: 'TULLETT PREBON BRASIL CVC LTDA',
  },
  { longName: 'ICBC do Brasil Banco Múltiplo S.A.', shortName: 'ICBC DO BRASIL BM S.A.' },
  {
    longName: 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E',
    shortName: 'CRESOL CONFEDERAÇÃO',
  },
  {
    longName: 'BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    shortName: 'BGC LIQUIDEZ DTVM LTDA',
  },
  {
    longName: 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. - UNICRED DO BRASI',
    shortName: 'CONF NAC COOP CENTRAIS UNICRED',
  },
  { longName: 'Get Money Corretora de Câmbio S.A.', shortName: 'GET MONEY CC LTDA' },
  {
    longName: 'Intesa Sanpaolo Brasil S.A. - Banco Múltiplo',
    shortName: 'INTESA SANPAOLO BRASIL S.A. BM',
  },
  { longName: 'Easynvest - Título Corretora de Valores SA', shortName: 'EASYNVEST - TÍTULO CV SA' },
  { longName: 'Broker Brasil Corretora de Câmbio Ltda.', shortName: 'BROKER BRASIL CC LTDA.' },
  { longName: 'Treviso Corretora de Câmbio S.A.', shortName: 'TREVISO CC S.A.' },
  { longName: 'BEXS BANCO DE CÂMBIO S/A', shortName: 'BEXS BCO DE CAMBIO S.A.' },
  { longName: 'LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA.', shortName: 'LEVYCAM CCV LTDA' },
  { longName: 'GUITTA CORRETORA DE CAMBIO LTDA.', shortName: 'GUITTA CC LTDA' },
  {
    longName: 'Facta Financeira S.A. - Crédito Financiamento e Investimento',
    shortName: 'FACTA S.A. CFI',
  },
  {
    longName: 'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.',
    shortName: 'ICAP DO BRASIL CTVM LTDA.',
  },
  {
    longName: 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor',
    shortName: 'CASA CREDITO S.A. SCM',
  },
  {
    longName: 'Commerzbank Brasil S.A. - Banco Múltiplo',
    shortName: 'COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO',
  },
  {
    longName: 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.',
    shortName: 'BRL TRUST DTVM SA',
  },
  {
    longName: 'PEFISA S.A. - CRÉDITO FINANCIAMENTO E INVESTIMENTO',
    shortName: 'PEFISA S.A. - CFI',
  },
  { longName: 'Guide Investimentos S.A. Corretora de Valores', shortName: 'GUIDE' },
  {
    longName: 'CM CAPITAL MARKETS CORRETORA DE CÂMBIO TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    shortName: 'CM CAPITAL MARKETS CCTVM LTDA',
  },
  {
    longName: 'SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P',
    shortName: 'SOCRED SA - SCMEPP',
  },
  { longName: 'Banco Itaú BBA S.A.', shortName: 'BCO ITAÚ BBA S.A.' },
  {
    longName: 'ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS CÂMBIO E VALORES',
    shortName: 'ATIVA S.A. INVESTIMENTOS CCTVM',
  },
  {
    longName: 'HS FINANCEIRA S/A CREDITO FINANCIAMENTO E INVESTIMENTOS',
    shortName: 'HS FINANCEIRA',
  },
  {
    longName: 'SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN',
    shortName: 'SERVICOOP',
  },
  {
    longName: 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.',
    shortName: 'NOVA FUTURA CTVM LTDA.',
  },
  {
    longName: 'PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    shortName: 'PARMETAL DTVM LTDA',
  },
  { longName: 'FAIR CORRETORA DE CAMBIO S.A.', shortName: 'FAIR CC S.A.' },
  { longName: 'Stone Pagamentos S.A.', shortName: 'STONE PAGAMENTOS S.A.' },
  { longName: 'Banco BTG Pactual S.A.', shortName: 'BANCO BTG PACTUAL S.A.' },
  { longName: 'Banco Original S.A.', shortName: 'BANCO ORIGINAL' },
  { longName: 'Banco Arbi S.A.', shortName: 'BCO ARBI S.A.' },
  { longName: 'Banco John Deere S.A.', shortName: 'BANCO JOHN DEERE S.A.' },
  { longName: 'Banco BS2 S.A.', shortName: 'BCO BS2 S.A.' },
  { longName: 'Banco Credit Agricole Brasil S.A.', shortName: 'BCO CRÉDIT AGRICOLE BR S.A.' },
  { longName: 'Banco Fibra S.A.', shortName: 'BCO FIBRA S.A.' },
  { longName: 'Banco Cifra S.A.', shortName: 'BANCO CIFRA' },
  { longName: 'Banco Bradesco S.A.', shortName: 'BCO BRADESCO S.A.' },
  { longName: 'BANCO CLASSICO S.A.', shortName: 'BCO CLASSICO S.A.' },
  { longName: 'BANCO MASTER S/A', shortName: 'BANCO MASTER' },
  { longName: 'Banco ABC Brasil S.A.', shortName: 'BCO ABC BRASIL S.A.' },
  { longName: 'Banco Investcred Unibanco S.A.', shortName: 'BANCO INVESTCRED UNIBANCO S.A.' },
  {
    longName: 'BCV - BANCO DE CRÉDITO E VAREJO S.A.',
    shortName: '"BCV - BCO CRÉDITO E VAREJO S.A.                            "',
  },
  { longName: 'Bexs Corretora de Câmbio S/A', shortName: 'BEXS CC S.A.' },
  { longName: 'PARANÁ BANCO S.A.', shortName: 'PARANA BCO S.A.' },
  { longName: 'MONEYCORP BANCO DE CÂMBIO S.A.', shortName: 'MONEYCORP BCO DE CÂMBIO S.A.' },
  { longName: 'Nu Pagamentos S.A.', shortName: 'NU PAGAMENTOS S.A.' },
  { longName: 'Banco Fator S.A.', shortName: 'BCO FATOR S.A.' },
  { longName: 'BANCO CEDULA S.A.', shortName: 'BCO CEDULA S.A.' },
  { longName: 'BARI COMPANHIA HIPOTECÁRIA', shortName: 'BARI CIA HIPOTECÁRIA' },
  { longName: 'BANCO HSBC S.A.', shortName: 'BCO HSBC S.A.' },
  { longName: 'Sagitur Corretora de Câmbio Ltda.', shortName: 'SAGITUR CC LTDA' },
  {
    longName: 'IB Corretora de Câmbio Títulos e Valores Mobiliários S.A.',
    shortName: 'IB CCTVM S.A.',
  },
  { longName: 'AGK CORRETORA DE CAMBIO S.A.', shortName: 'AGK CC S.A.' },
  {
    longName: 'Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel',
    shortName: 'CCR DE SÃO MIGUEL DO OESTE',
  },
  {
    longName: 'MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT',
    shortName: 'MONEY PLUS SCMEPP LTDA',
  },
  { longName: 'BANCO SENFF S.A.', shortName: 'BCO SENFF S.A.' },
  {
    longName: 'Genial Investimentos Corretora de Valores Mobiliários S.A.',
    shortName: 'GENIAL INVESTIMENTOS CVM S.A.',
  },
  {
    longName: 'COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE',
    shortName: 'CCR DE PRIMAVERA DO LESTE',
  },
  {
    longName: 'WILL FINANCEIRA S.A. CRÉDITO FINANCIAMENTO E INVESTIMENTO',
    shortName: 'WILL FINANCEIRA S.A.CFI',
  },
  { longName: 'Cooperativa de Crédito Rural Coopavel', shortName: 'CCR COOPAVEL' },
  {
    longName: 'RB INVESTIMENTOS DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LIMITADA',
    shortName: 'RB INVESTIMENTOS DTVM LTDA.',
  },
  { longName: 'Frente Corretora de Câmbio Ltda.', shortName: 'FRENTE CC LTDA.' },
  { longName: 'COOPERATIVA DE CRÉDITO RURAL DE OURO   SULCREDI/OURO', shortName: 'CCR DE OURO' },
  {
    longName: 'CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
    shortName: 'CAROL DTVM LTDA.',
  },
  { longName: 'DECYSEO CORRETORA DE CAMBIO LTDA.', shortName: 'DECYSEO CC LTDA.' },
  { longName: 'Pagseguro Internet S.A.', shortName: 'PAGSEGURO S.A.' },
  {
    longName: 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.',
    shortName: 'BS2 DTVM S.A.',
  },
  {
    longName: 'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.',
    shortName: 'LASTRO RDV DTVM LTDA',
  },
  { longName: 'VISION S.A. CORRETORA DE CAMBIO', shortName: 'VISION S.A. CC' },
  { longName: "Vip's Corretora de Câmbio Ltda.", shortName: 'VIPS CC LTDA.' },
  { longName: 'BANCO SOROCRED S.A. - BANCO MÚLTIPLO', shortName: 'BCO SOROCRED S.A. - BM' },
  { longName: 'Banco de la Nacion Argentina', shortName: 'BCO LA NACION ARGENTINA' },
  { longName: 'BPP Instituição de Pagamento S.A.', shortName: 'BPP IP S.A.' },
  {
    longName: 'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
    shortName: 'PORTOPAR DTVM LTDA',
  },
  {
    longName: 'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.',
    shortName: 'TERRA INVESTIMENTOS DTVM',
  },
  { longName: 'CAMBIONET CORRETORA DE CÂMBIO LTDA.', shortName: 'CAMBIONET CC LTDA' },
  {
    longName: 'VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
    shortName: 'VORTX DTVM LTDA.',
  },
  { longName: 'DOURADA CORRETORA DE CÂMBIO LTDA.', shortName: 'DOURADA CORRETORA' },
  {
    longName: 'HSCM - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LT',
    shortName: 'HSCM SCMEPP LTDA.',
  },
  { longName: 'AMAZÔNIA CORRETORA DE CÂMBIO LTDA.', shortName: 'AMAZÔNIA CC LTDA.' },
  { longName: 'PI Distribuidora de Títulos e Valores Mobiliários S.A.', shortName: 'PI DTVM S.A.' },
  { longName: 'Banco BMG S.A.', shortName: 'BCO BMG S.A.' },
  { longName: 'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA', shortName: 'OM DTVM LTDA' },
  {
    longName: 'China Construction Bank (Brasil) Banco Múltiplo S/A',
    shortName: 'BCO CCB BRASIL S.A.',
  },
  {
    longName: 'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT',
    shortName: 'CREFAZ SCMEPP LTDA',
  },
  {
    longName: 'Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz',
    shortName: 'CCR DE ABELARDO LUZ',
  },
  { longName: 'MERCADOPAGO.COM REPRESENTACOES LTDA.', shortName: 'MERCADO PAGO' },
  { longName: 'CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'CARTOS SCD S.A.' },
  {
    longName: 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.',
    shortName: 'ÓRAMA DTVM S.A.',
  },
  {
    longName: 'PARATI - CREDITO FINANCIAMENTO E INVESTIMENTO S.A.',
    shortName: 'PARATI - CFI S.A.',
  },
  {
    longName: 'COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS FABRICANTES DE CALÇADOS DE SAPIRANGA',
    shortName: 'CECM FABRIC CALÇADOS SAPIRANGA',
  },
  { longName: 'QI Sociedade de Crédito Direto S.A.', shortName: 'QI SCD S.A.' },
  { longName: 'BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.', shortName: 'BANCO BARI S.A.' },
  {
    longName: 'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.',
    shortName: 'FRAM CAPITAL DTVM S.A.',
  },
  { longName: 'Acesso Soluções de Pagamento S.A.', shortName: 'ACESSO SOLUCOES PAGAMENTO SA' },
  { longName: 'Banco Digio S.A.', shortName: 'BANCO DIGIO' },
  { longName: 'Banco C6 S.A.', shortName: 'BCO C6 S.A.' },
  {
    longName: 'Super Pagamentos e Administração de Meios Eletrônicos S.A.',
    shortName: 'SUPER PAGAMENTOS E ADMINISTRACAO DE MEIOS ELETRONICOS S.A.',
  },
  { longName: 'ITAÚ UNIBANCO S.A.', shortName: 'ITAÚ UNIBANCO S.A.' },
  { longName: 'Creditas Sociedade de Crédito Direto S.A.', shortName: 'CREDITAS SCD' },
  {
    longName: 'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.',
    shortName: 'FFA SCMEPP LTDA.',
  },
  { longName: 'Banco XP S.A.', shortName: 'BCO XP S.A.' },
  { longName: 'AL5 S.A. CRÉDITO FINANCIAMENTO E INVESTIMENTO', shortName: 'AL5 S.A. CFI' },
  {
    longName: 'COOPERATIVA DE CRÉDITO RURAL DE PEQUENOS AGRICULTORES E DA REFORMA AGRÁRIA DO CE',
    shortName: 'CREHNOR LARANJEIRAS',
  },
  { longName: 'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA', shortName: 'TORO CTVM LTDA' },
  {
    longName: 'NECTON INVESTIMENTOS  S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES',
    shortName: 'NECTON INVESTIMENTOS S.A CVM',
  },
  { longName: 'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'ÓTIMO SCD S.A.' },
  {
    longName: 'MIDWAY S.A. - CRÉDITO FINANCIAMENTO E INVESTIMENTO',
    shortName: 'MIDWAY S.A. - SCFI',
  },
  { longName: 'ZEMA CRÉDITO FINANCIAMENTO E INVESTIMENTO S/A', shortName: 'ZEMA CFI S/A' },
  {
    longName: 'TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
    shortName: 'TRINUS CAPITAL DTVM',
  },
  { longName: 'CIELO S.A.', shortName: 'CIELO S.A.' },
  {
    longName: 'SINGULARE CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
    shortName: 'SINGULARE CTVM S.A.',
  },
  { longName: 'GERENCIANET S.A.', shortName: 'GERENCIANET' },
  { longName: 'SIMPAUL CORRETORA DE CAMBIO E VALORES MOBILIARIOS  S.A.', shortName: 'SIMPAUL' },
  { longName: 'BANCO SOCIETE GENERALE BRASIL S.A.', shortName: 'BCO SOCIETE GENERALE BRASIL' },
  {
    longName: 'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
    shortName: 'VITREO DTVM S.A.',
  },
  { longName: 'Banco CSF S.A.', shortName: 'BCO CSF S.A.' },
  { longName: 'Banco Mizuho do Brasil S.A.', shortName: 'BCO MIZUHO S.A.' },
  {
    longName: 'WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.',
    shortName: 'WARREN CVMC LTDA',
  },
  { longName: 'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.', shortName: 'UP.P SEP S.A.' },
  { longName: 'REALIZE CRÉDITO FINANCIAMENTO E INVESTIMENTO S.A.', shortName: 'REALIZE CFI S.A.' },
  { longName: 'BANCO J.P. MORGAN S.A.', shortName: 'BCO J.P. MORGAN S.A.' },
  { longName: 'BMS SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'BMS SCD S.A.' },
  { longName: 'BBC LEASING S.A. - ARRENDAMENTO MERCANTIL', shortName: 'BBC LEASING' },
  {
    longName: 'COOPERFORTE - COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DE FUNCIONÁRIOS DE INSTITU',
    shortName: 'CECM COOPERFORTE',
  },
  { longName: 'PICPAY SERVICOS S.A.', shortName: 'PICPAY' },
  { longName: 'BANCO MERCEDES-BENZ DO BRASIL S.A.', shortName: 'BCO MERCEDES-BENZ S.A.' },
  {
    longName: 'FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE L',
    shortName: 'FIDUCIA SCMEPP LTDA',
  },
  { longName: 'BOLETOBANCÁRIO.COM TECNOLOGIA DE PAGAMENTOS LTDA.', shortName: 'JUNO' },
  {
    longName: 'GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO',
    shortName: 'GLOBAL SCM LTDA',
  },
  {
    longName: 'NU FINANCEIRA S.A. - Sociedade de Crédito Financiamento e Investimento',
    shortName: 'NU FINANCEIRA S.A. CFI',
  },
  { longName: 'Banco Toyota do Brasil S.A.', shortName: 'BCO TOYOTA DO BRASIL S.A.' },
  { longName: 'Banco Mercantil do Brasil S.A.', shortName: 'BCO MERCANTIL DO BRASIL S.A.' },
  { longName: 'BANCO GM S.A.', shortName: 'BCO GM S.A.' },
  { longName: 'COOPERATIVA DE CREDITO RURAL DE IBIAM - SULCREDI/IBIAM', shortName: 'CCR DE IBIAM' },
  { longName: 'Banco Volkswagen S.A.', shortName: 'BCO VOLKSWAGEN S.A' },
  { longName: 'Banco Bradesco Financiamentos S.A.', shortName: 'BCO BRADESCO FINANC. S.A.' },
  {
    longName: "F.D'GOLD - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.",
    shortName: 'F D GOLD DTVM LTDA',
  },
  { longName: 'HUB PAGAMENTOS S.A', shortName: 'HUB PAGAMENTOS' },
  { longName: 'LISTO SOCIEDADE DE CREDITO DIRETO S.A.', shortName: 'LISTO SCD S.A.' },
  {
    longName: 'IDEAL CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
    shortName: 'IDEAL CTVM S.A.',
  },
  { longName: 'Kirton Bank S.A. - Banco Múltiplo', shortName: 'KIRTON BANK' },
  {
    longName: 'COOPERATIVA DE CRÉDITO POUPANÇA E SERVIÇOS FINANCEIROS DO CENTRO OESTE',
    shortName: 'CC POUP SER FIN CO',
  },
  { longName: 'IUGU INSTITUIÇÃO DE PAGAMENTO S.A.', shortName: 'IUGU IP S.A.' },
  { longName: 'COBUCCIO SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'COBUCCIO SCD S.A.' },
  { longName: 'CORA SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'CORA SCD S.A.' },
  { longName: 'SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'SUMUP SCD S.A.' },
  { longName: 'ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'ACCREDITO SCD S.A.' },
  {
    longName: 'ÍNDIGO INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.',
    shortName: 'ÍNDIGO INVESTIMENTOS DTVM LTDA.',
  },
  { longName: 'BONUSPAGO SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'BONUSPAGO SCD S.A.' },
  {
    longName: 'PLANNER SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR S.A.',
    shortName: 'PLANNER SCM S.A.',
  },
  {
    longName: 'Via Certa Financiadora S.A. - Crédito Financiamento e Investimentos',
    shortName: 'VIA CERTA FINANCIADORA S.A. - CFI',
  },
  { longName: 'BANCO CAPITAL S.A.', shortName: 'BCO CAPITAL S.A.' },
  { longName: 'BANCO BV S.A.', shortName: 'BCO BV S.A.' },
  { longName: 'WORK SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'WORK SCD S.A.' },
  { longName: 'LAMARA SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'LAMARA SCD S.A.' },
  { longName: 'NUMBRS SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'NUMBRS SCD S.A.' },
  { longName: 'LAR COOPERATIVA DE CRÉDITO - LAR CREDI', shortName: 'CC LAR CREDI' },
  { longName: 'Banco Safra S.A.', shortName: 'BCO SAFRA S.A.' },
  {
    longName: 'COLUNA S/A DISTRIBUIDORA DE TITULOS E VALORES MOBILIÁRIOS',
    shortName: 'COLUNA S.A. DTVM',
  },
  {
    longName: 'SOCINAL S.A. - CRÉDITO FINANCIAMENTO E INVESTIMENTO',
    shortName: 'SOCINAL S.A. CFI',
  },
  {
    longName: 'Biorc Financeira - Crédito Financiamento e Investimento S.A.',
    shortName: 'BIORC FINANCEIRA - CFI S.A.',
  },
  {
    longName: 'COOPERATIVA DE CREDITO DOS SERVIDORES DA UNIVERSIDADE FEDERAL DO ESPIRITO SANTO',
    shortName: 'CRED-UFES',
  },
  { longName: 'CRED-SYSTEM SOCIEDADE DE CRÉDITO DIRETO S.A.', shortName: 'CRED-SYSTEM SCD S.A.' },
  {
    longName: 'BR-CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
    shortName: 'BR-CAPITAL DTVM S.A.',
  },
  {
    longName: 'PLANNER TRUSTEE DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.',
    shortName: 'PLANNER TRUSTEE DTVM LTDA',
  },
  { longName: 'PLANTAE S.A. - CRÉDITO FINANCIAMENTO E INVESTIMENTO', shortName: 'PLANTAE CFI' },
  {
    longName: 'FITBANK PAGAMENTOS ELETRONICOS S.A.',
    shortName: 'FITBANK PAGAMENTOS ELETRONICOS S.A.',
  },
  { longName: 'Banco MUFG Brasil S.A.', shortName: 'BCO MUFG BRASIL S.A.' },
  {
    longName: 'Banco Sumitomo Mitsui Brasileiro S.A.',
    shortName: 'BCO SUMITOMO MITSUI BRASIL S.A.',
  },
  { longName: 'Banco Caixa Geral - Brasil S.A.', shortName: 'BCO CAIXA GERAL BRASIL S.A.' },
  { longName: 'Citibank N.A.', shortName: 'CITIBANK N.A.' },
  { longName: 'Banco ItauBank S.A.', shortName: 'BCO ITAUBANK S.A.' },
  { longName: 'Deutsche Bank S.A. - Banco Alemão', shortName: 'DEUTSCHE BANK S.A.BCO ALEMAO' },
  { longName: 'JPMorgan Chase Bank National Association', shortName: 'JPMORGAN CHASE BANK' },
  { longName: 'ING Bank N.V.', shortName: 'ING BANK N.V.' },
  { longName: 'Banco de La Provincia de Buenos Aires', shortName: 'BCO LA PROVINCIA B AIRES BCE' },
  { longName: 'Banco Credit Suisse (Brasil) S.A.', shortName: 'BCO CREDIT SUISSE S.A.' },
  { longName: 'SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A', shortName: 'SENSO CCVM S.A.' },
  { longName: 'Banco Luso Brasileiro S.A.', shortName: 'BCO LUSO BRASILEIRO S.A.' },
  { longName: 'Banco Industrial do Brasil S.A.', shortName: 'BCO INDUSTRIAL DO BRASIL S.A.' },
  { longName: 'Banco VR S.A.', shortName: 'BCO VR S.A.' },
  { longName: 'Banco Paulista S.A.', shortName: 'BCO PAULISTA S.A.' },
  { longName: 'Banco Guanabara S.A.', shortName: 'BCO GUANABARA S.A.' },
  { longName: 'Omni Banco S.A.', shortName: 'OMNI BANCO S.A.' },
  { longName: 'Banco Pan S.A.', shortName: 'BANCO PAN' },
  { longName: 'BANCO C6 CONSIGNADO S.A.', shortName: 'BCO C6 CONSIG' },
  { longName: 'Banco Smartbank S.A.', shortName: 'SMARTBANK' },
  { longName: 'Banco Rendimento S.A.', shortName: 'BCO RENDIMENTO S.A.' },
  { longName: 'BANCO TRIANGULO S.A.', shortName: 'BCO TRIANGULO S.A.' },
  { longName: 'BANCO SOFISA S.A.', shortName: 'BCO SOFISA S.A.' },
  { longName: 'Banco Pine S.A.', shortName: 'BCO PINE S.A.' },
  { longName: 'Itaú Unibanco Holding S.A.', shortName: 'ITAÚ UNIBANCO HOLDING S.A.' },
  { longName: 'BANCO VOITER S.A.', shortName: 'BANCO VOITER' },
  { longName: 'BANCO DIGIMAIS S.A.', shortName: 'BCO DIGIMAIS S.A.' },
  { longName: 'Banco Votorantim S.A.', shortName: 'BCO VOTORANTIM S.A.' },
  { longName: 'Banco Daycoval S.A.', shortName: 'BCO DAYCOVAL S.A' },
  { longName: 'Banco Ourinvest S.A.', shortName: 'BCO OURINVEST S.A.' },
  { longName: 'BANCO RNX S.A.', shortName: 'BCO RNX S.A.' },
  { longName: 'Banco Cetelem S.A.', shortName: 'BCO CETELEM S.A.' },
  { longName: 'BANCO RIBEIRAO PRETO S.A.', shortName: 'BCO RIBEIRAO PRETO S.A.' },
  { longName: 'Banco Semear S.A.', shortName: 'BANCO SEMEAR' },
  { longName: 'Banco Citibank S.A.', shortName: 'BCO CITIBANK S.A.' },
  { longName: 'Banco Modal S.A.', shortName: 'BCO MODAL S.A.' },
  {
    longName: 'Banco Rabobank International Brasil S.A.',
    shortName: 'BCO RABOBANK INTL BRASIL S.A.',
  },
  { longName: 'BANCO COOPERATIVO SICREDI S.A.', shortName: 'BCO COOPERATIVO SICREDI S.A.' },
  { longName: 'Scotiabank Brasil S.A. Banco Múltiplo', shortName: 'SCOTIABANK BRASIL' },
  { longName: 'Banco BNP Paribas Brasil S.A.', shortName: 'BCO BNP PARIBAS BRASIL S A' },
  {
    longName: 'Novo Banco Continental S.A. - Banco Múltiplo',
    shortName: 'NOVO BCO CONTINENTAL S.A. - BM',
  },
  { longName: 'Banco Sistema S.A.', shortName: 'BANCO SISTEMA' },
  {
    longName: 'Bank of America Merrill Lynch Banco Múltiplo S.A.',
    shortName: 'BOFA MERRILL LYNCH BM S.A.',
  },
  { longName: 'BANCO COOPERATIVO SICOOB S.A. - BANCO SICOOB', shortName: 'BANCO SICOOB S.A.' },
  { longName: 'BANCO KEB HANA DO BRASIL S.A.', shortName: 'BCO KEB HANA DO BRASIL S.A.' },
].sort((a, b) => {
  return a.shortName > b.shortName ? 1 : -1
})
